### ISSUE TITLE
Add a latest/current tag

### ISSUE THREAD

**Issue by billinghamj** [CircleCI-Public/cimg-go#103]
We use the `current` tag on `cimg/node` and find it very useful to ensure we're always 100% up to date on the latest releases. As we use Dependabot on our dockerfiles, but Dependabot can't keep track of the images referenced in our CircleCI config of course.

Could you please add an equivalent `current` or `latest` tag to this one?

Obviously it would be expected that breaking changes etc could break our builds, but that's totally fine - that's what we'd want it to do, same as with Node 👍

Thanks

**Comment by billinghamj** [comment]
Just bumping this @felicianotech

**Comment by felicianotech** [comment]
Hey. So there's no current plans to do this. This is something we're aware of though and will be considering depending on future feedback.

There's two main reasons why don't have this currently:

1. "Obviously it would be expected that breaking changes etc could break our builds" You would think this is obvious. It's not always the case and we've had many complains with users of older images and other things where this occurs.
2. There's a small technical challenge as to what is "current" or "latest". For many language projects, they will release minor or patch releases for older releases. Using Go as an example, If they release v1.15.5 today, that would be "latest". If next week they discover a security bug that's only present in the v1.13.x series, they may release Go v1.13.16 with a fix. In our current build system, that would then be marked as the latest release which is clearly not what you as a customer would want.

The Node.js image has `current` and `lts` alias tags as a special one off. This is because they support these terms 1st-party: https://nodejs.org/en/

So we'll consider this but there's no immediate plans.
