### ISSUE TITLE
Plan to docker compose v2

### ISSUE THREAD

**Issue by EduardoLaranjo** [CircleCI-Public/cimg-go#143]
Hi,
Since the new base image cimg:2021.12 has docker compose v2,  Is there a plan to update?

Source:
https://discuss.circleci.com/t/docker-compose-v2-now-in-cimg-base/42184

**Comment by JalexChen** [comment]
Hi Eduardo,

The reason why it's not explicitly included in the Go image is due to Compose v2 being a broad change that affects all images, therefore the change was made in the base cimg, which is what the Go image is built off of. This was recently updated to support Docker Compose v2 as well as Docker Switch, offering compatibility even when using docker-compose (vs docker compose). 

I've just tested this out on my end and is working. If you run into any issues, please don't hesitate to bring it up!

If you'd like to reference this, it should be on lines 101-113 [here](https://github.com/CircleCI-Public/cimg-base/blob/main/Dockerfile.template)

**Comment by JalexChen** [comment]
Hi Eduardo,

The changes were recently made to the monthly image update, which is available at cimg:2022.1. 

Since these are snapshots, please utilize the the new image, which includes both Compose Switch and Compose v2.

**Comment by felicianotech** [comment]
Let us know if you have any further questions. :)

**Comment by EduardoLaranjo** [comment]
Thanks for the quick response 👍
