### ISSUE TITLE
[1.17] Unpinned minor version breaking pipeline

### ISSUE THREAD

**Issue by Todai88** [CircleCI-Public/cimg-go#171]
### Description
We’ve noticed an issue when using an unpinned (minor) version of your `cimg/go/`  image (e.g: `1.17`). We are reasonably confident this relates to dependencies in your docker image, and nothing on our end.

The latest minor version resolves to `1.17.9` , which is producing this error in our CCI pipeline (where we are `docker-compose`:ing):

> [+] Building 0.0s (0/0)                                                         
listing workers for Build: failed to list workers: Unavailable: connection error: desc = "transport: Error while dialing unable to upgrade to h2c, received 404"

This error is consistent with messages in your [public forums](https://app.circleci.com/pipelines/github/snyk/sbom-export/43/workflows/dc2afa4f-0172-4ba4-b885-42d6806541da/jobs/164), and seems to be a “sort of” known issue (though there’s no CCI :ack: on the issue!).

### Manual workaround (short-term fix)
Our workaround is to pin the minor version to `1.17.8`, which resolves the error. But this creates a problem for our migration to 1.18 - which is also producing the aforementioned error.

### Expected Behaviour
* CCI's `go` image should not break our pipeline when minor version isn't manually pinned
* Our migration to `go` `1.18` should be unaffected by CCI images.

**Comment by felicianotech** [comment]
Hey. Thank you for reaching out. Here's some thoughts:

1. If you're worried about changes, a tag that doesn't change should be used. Currently you are using an alias tag which is designed to change overtime.
2. Very little changed in the image from v1.17.8 to 1.17.9. The largest change is the Go version. Perhaps your project isn't happy with that version of Go? That wouldn't be our issue. The most common cause when I see this issue, if it isn't Go itself, is when the customer is caching Go components but the cache key doesn't take the Go version into account and break things. May that be it?
3. Just in case #2 is not correct, I'll do some more digging.
4. The last line of your issue mentions Go 1.18 but the rest mentions 1.17.9. Which are you actually trying out? I want to make sure I am debugging the correct image tag.
5. The link you changed isn't a forum link but a build link. Was that intentional?

**Comment by jenny-miggin** [comment]
Regarding point 5, I'm sharing the [correct link](https://discuss.circleci.com/t/fail-to-build-images-with-docker-compose/43678)

**Comment by felicianotech** [comment]
Haven't been able to reproduce nor seen other recent complaints about this. Closing.
